### ISSUE TITLE
Help with exceptions when converting a LeMond GT csv file.

### ISSUE THREAD

**Issue by Rowdyrc** [tpodowd/lemondcsv#6]
Hi Tom 
Not sure if you remember this program you wrote a long time ago.

I have a LeMond GT UT which appears to output a csv file very similar to the Revolution so I was hoping that your program might enable me to convert my files for Garmin/Strava upload.

I've run the program on my csv file and got 4 exceptions which I've tried to debug but know absolutely nothing about Python and straight logic hasn't helped. 

I've installed Python 3.3. 

I've attached my csv file and a screen shot of the exceptions - any advice on how to resolve the issues would be gratefully received.

Thanks in advance
Roman
[05092200.CSV](https://github.com/tpodowd/lemondcsv/files/8656592/05092200.CSV)
[Lemond.py exceptions.txt](https://github.com/tpodowd/lemondcsv/files/8656601/Lemond.py.exceptions.txt)

**Comment by tpodowd** [comment]
Hi @Rowdyrc - Sorry for the delay... (he says over 2 years later). I haven't looked at this code in years. I don't know why I missed your issue but I guess this is not exactly a busy repo. Did you solve your issue? If not let me know and I'll take a look for you.

**Comment by tpodowd** [comment]
I went out for a beer with a friend tonight and when I came back. I decided to add support for your LeMond GT file. Please try the latest release. I added a new script called `lemondcsv_gt.py` as I no longer have any of the older sample files on which to validate changes to the existing code. It was easier to add a new modified script. Even if you don't need it any more, maybe someone will benefit. Happy training!
